### ISSUE TITLE
Context menu does not show up menu item

### ISSUE THREAD

**Issue by maltebeyer** [MattesGroeger/chrome-open-links#25]
Probably I am too dumb, but in my context menu no menu item shows up. I installed the extension and restarted Chrome. Afterwards I selected some google result links and clicked the right mouse button. I cannot see any menu item belonging to this extension. See attached screenshots (one shows that extension is installed, the other shows the context menu).

Chrome 24.0.1312.52, German
Mac OS X 10.8.2

![Bildschirmfoto 2013-01-18 um 09 14 33](https://f.cloud.github.com/assets/1913578/77554/bba3f130-6148-11e2-9daa-6c152bc1b2c4.png)
![Bildschirmfoto 2013-01-18 um 09 14 56](https://f.cloud.github.com/assets/1913578/77555/bba4c0f6-6148-11e2-85c0-9a6b552fbe92.png)

**Comment by MattesGroeger** [comment]
Hi Malte, thanks for reporting this issue. Did you reload the webpage after installing the extension? If not, could you please try again? That is because a small js-script needs to be injected into the page in order to talk to the extension.
