### ISSUE TITLE
Cannot open selected links in local files

### ISSUE THREAD

**Issue by gresh28** [MattesGroeger/chrome-open-links#31]
Steps to repo:
1. Open any web page from the local file system (file:///) in Chrome (Version 34.0.1847.137 m)
2. Ctr+A to select the entire contents of the page, including any links
3. Right-click and try to open selected links

Result:
- No links are detected
  ![untitled](https://cloud.githubusercontent.com/assets/7598099/2992732/349e7f10-dc9a-11e3-84a7-4830e5020e5a.jpg)

Expected:
- Links should be detected and be available in the right-click menu

**Comment by MattesGroeger** [comment]
Thanks for your report @gresh28. It looks like local files [are supported nowadays](https://developer.chrome.com/extensions/match_patterns). I will give it a try and deploy a new version if it works.

**Comment by MattesGroeger** [comment]
Works now with the latest version (1.0.4), but you have to manually activate the permission "Allow access to file URLs" on the extension page:

![screen shot 2014-05-17 at 02 30 00](https://cloud.githubusercontent.com/assets/187211/3003641/6ebd9526-dd5a-11e3-9511-3122d72cc671.png)
