### ISSUE TITLE
UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL

### ISSUE THREAD

**Issue by nemobis** [MattesGroeger/chrome-open-links#36]
I got this error when trying to install 1.0.5 on the last Chrom(e|ium) stable, 38.0.2125.101 Russian Fedora (290379) (64-bit).

I have other extensions installed

**Comment by nemobis** [comment]
Nevermind, happened with another extension as well, my problem I guess

**Comment by nemobis** [comment]
And it works in 39.0.2171.71 :)

**Comment by MattesGroeger** [comment]
Great :+1:
